on: push

name: Test

jobs:
  print-opts:
    name: Print options
    runs-on: ubuntu-latest
    steps:
      - name: Print options
        shell: bash
        run: printf %s\\n "$-"

  test-opts:
    name: Test with options
    runs-on: ubuntu-latest
    steps:
      - name: Undefined var
        shell: bash
        if: always()
        run: |
          set -eoux pipefail

          echo "${UNDEFINED}"
      - name: Piping fail
        shell: bash
        if: always()
        run: |
          set -eoux pipefail

          echo "Oh no i am piping an the next fails" | exit 1 | echo "Will i make it here?"

  test-noopts:
    name: Test without options
    runs-on: ubuntu-latest
    steps:
      - name: Undefined var
        shell: bash
        if: always()
        run: |
          echo "${UNDEFINED}"
      - name: Piping fail
        shell: bash
        if: always()
        run: |
          echo "Oh no i am piping an the next fails" | exit 1 | echo "Will i make it here?"
