name: CI 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run typos with reviewdog
        uses: Shemnei/reviewdog-action-typos@v0
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          level: warning
          files: |
            README.md
            src/main.rs
          exclude: |
            *.rs
          extend_identifiers: test
          isolated: true
          config: .github/asdf.txt

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
