name: reviewdog
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typos:
    name: runner / typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - name: Run typos with reviewdog
        uses: Shemnei/reviewdog-action-typos@v0.1.0
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          level: warning
